services:
  brille24_tier_price.tierprice_factory:
    class: Brille24\SyliusTierPricePlugin\Factory\TierPriceExampleFactory
    arguments: ['@sylius.repository.product_variant', '@sylius.repository.channel']
